import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { NextAuthProvider } from './components/Providers'
import { getServerSession } from 'next-auth'
import { authOptions } from './lib/auth'
import Image from 'next/image'
import { Login, Logout } from './components/Buttons'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Chat App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions)
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <nav className='flex justify-between items-center px-10 py-5 fixed top-0 left-0 w-full bg-white'>
            <h1 className='text-3xl font-extrabold text-sky-950'>Rohit&apos;s <span className='text-red-500'>Chat</span></h1>
            {session ? (
              <div className='flex items-center gap-6'>
                <Image
                  src={session.user?.image as string}
                  alt="profile image"
                  className="w-12 h-12 rounded-full mr-3"
                  width={50}
                  height={50}
                />
                <Logout />
              </div>
            ): (
              <Login />
            )}
          </nav>
          <main>{children}</main>
        </NextAuthProvider>
      </body>
    </html>
  )
}
